name: Github Actions
on:
  push:
    branches:
      - dev
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        run: echo "Hello, World!"
      - name: My second step
        run: date
      - name: My third step
        env:
          PROJECT: "CI/CD"
        run: echo "This is a $PROJECT pipeline"
      - name: Github Repo
        run: |
          echo "Gihub Repo : ${{github.repository}}"
          echo "Github Branch : ${{github.ref}}"

  test-job:
    runs-on: "ubuntu-latest"
    needs: my-job
    steps:
      - name: Running Test Job
        run: echo "running tests"
